-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "tracksInventory" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "isPriceEditable" BOOLEAN NOT NULL DEFAULT false;
